### ISSUE TITLE
Outdated plugin fluent-plugin-kafka

### ISSUE THREAD

**Issue by PushUpek** [bitnami/bitnami-docker-fluentd#15]
Last image `1.11.2-debian-10-r26` contains `fluent-plugin-kafka == 0.13.1`. Is there any chance to bump version of this plugin to `>= 0.14.2`? New version supports `add_headers` parameter.

**Comment by FraPazGal** [comment]
Hi @PushUpek,

Thanks for letting us know! We were using an older version of the plugin because we were using the same kafka binary since its last release (a couple of months old). We have updated the binary and it now contains the last version of the plugin, `fluent-plugin-kafka == 0.15.1`. 

The changes should be included in the today's or tomorrow's release of the container at the latest. Please let us know if it is so!

**Comment by PushUpek** [comment]
Yes, there is new version
`2020-09-21 06:07:04 +0000 [info]: gem 'fluent-plugin-kafka' version '0.15.1'`

thx!
