### ISSUE TITLE
Vulnerabilities in installed packages

### ISSUE THREAD

**Issue by ronenl3** [bitnami/bitnami-docker-fluentd#31]
**Description**

There are 2 packages installed in the [Dockerfile](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/Dockerfile#L11) that introduce high score vulnerabilities to the image. I'm not sure these packages are relevant to Fluentd at all and wanted to know why you need them in the image. The packages are `imagemagick` and `ghostscript`.

**Steps to reproduce the issue:**

Both of the packages are installed in the latest version.

**Comment by juan131** [comment]
Hi @ronenl3 

These packages are runtime dependencies.. So yes: we nee to ship them in the final image.

What scanner are you using to detect CVE(s)? Please note that these are system packages, therefore we can't do much more until Debian releases a new version of the packages patching any potential vulnerability. We do container releases on a daily basis so we should release an image including the patches as soon as they're published in Debian.

**Comment by ronenl3** [comment]
I'm using Snyk to scan CVEs, and found a vulnerability with Critical severity in `ghostscript` and some high severity vulnerabilities in `imagemagick `.
What is your usage in these packages? When looking on fluentd [image](https://github.com/fluent/fluentd-docker-image/blob/master/v1.14/debian/Dockerfile) I don't see them there. 
These packages seem to be unrelated to fluentd and they introduce vulns with a high score severity that doesn't have a fix for a while now

**Comment by juan131** [comment]
Hi @ronenl3 

It seems it's included because of Ruby.

When we compile our components (the ones we install in the image using `component_unpack ...` such as in [this example](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/Dockerfile#L12)) we use a tool that autogenerates what runtime dependencies the component will need (only considering runtime deps that we need to install using system packages). Our system collects the runtime deps of every component we need to build an image (in the Fluentd example: **ruby** + **gosu** + **fluentd**) and use that information to generate the list of deps you can see in the in the [`RUN install_packages ...` layer](https://github.com/bitnami/bitnami-docker-fluentd/blob/master/1/debian-10/Dockerfile#L11).

These are the runtime deps reported by our tool for Fluentd and Ruby:

- Fluentd runtime deps:

```json
    "systemPackages": [
        "libc6",
        "libgcc1",
        "libstdc++6"
    ]
````

- Ruby runtime deps:

```json
    "systemPackages": [
        "ghostscript",
        "imagemagick",
        "libc6",
        "libgmp-dev",
        "libncurses6",
        "libreadline-dev",
        "libreadline7",
        "libssl-dev",
        "libssl1.1",
        "libtinfo6",
        "libxml2-dev",
        "libxslt1-dev",
        "sqlite3",
        "zlib1g",
        "zlib1g-dev"
    ]
```

As you can see, both `ghostscript` and `imagemagick` are included because of Ruby.

**Comment by ronenl3** [comment]
@juan131 Got it, thanks for the clarification
